### ISSUE TITLE
Update Blue XP link to point to ontap repo instead of smclassic

### ISSUE THREAD

**Issue by netapp-aherbin** [NetAppDocs/bluexp-replication#24]
### Page URL

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html

### Page title

Set up data replication

### Summary

This link [View prerequisites for cluster peering in the ONTAP documentation](https://docs.netapp.com/us-en/ontap-sm-classic/peering/reference_prerequisites_for_cluster_peering.html) should be updated to point to the ONTAP 9 repo.

Suggested link: https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html#connectivity-requirements

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you, Amanda. I updated the link.
